version: "3"
services:
  smdb_front:
    container_name: lamesty_front
    build: .  
    ports:
      - "80:3000"
    command: bash -c "npm start"
    networks:
      - lamesty_meteo_net 
    external_links:
      - lamesty_db

networks:
   lamesty_meteo_net:  
     external: true
