export const types = {
  CHANGE_VISIBLE_LOADER: "CHANGE_VISIBLE_LOADER",
  SET_POLY_REQUEST: "SET_POLY_REQUEST",
  SET_MARKER_REQUEST: "SET_MARKER_REQUEST",
  SET_QUERY_REQUEST: "SET_QUERY_REQUEST",

  DISABLE_OFFSET_AND_LIMIT_BUTTON: "DISABLE_OFFSET_AND_LIMIT_BUTTON",
};

