export const types = {
  CHANGE_VISIBLE_LOADER: "CHANGE_VISIBLE_LOADER",
  IF_POLY_SELECTED: "IF_POLY_SELECTED",
  IF_MARKER_SELECTED: "IF_MARKER_SELECTED",
  ON_OFFSET_CHANGE: "ON_OFFSET_CHANGE",
  ON_LIMIT_CHANGE: "ON_LIMIT_CHANGE",
  DISABLE_OFFSET_AND_LIMIT_BUTTON: "DISABLE_OFFSET_AND_LIMIT_BUTTON",
};


//export const loaderVisibility = (flag) => ({type: types.CHANGE_VISIBLE_LOADER, flag});
