export const types = {
  CHANGE_VISIBLE_LOADER: "CHANGE_VISIBLE_LOADER",
  SET_POLY_REQUEST: "SET_POLY_REQUEST",
  SET_MARKER_REQUEST: "SET_MARKER_REQUEST",
  ON_OFFSET_CHANGE: "ON_OFFSET_CHANGE",
  ON_LIMIT_CHANGE: "ON_LIMIT_CHANGE",
  DISABLE_OFFSET_AND_LIMIT_BUTTON: "DISABLE_OFFSET_AND_LIMIT_BUTTON",
};


//export const loaderVisibility = (flag) => ({type: types.CHANGE_VISIBLE_LOADER, flag});
